# ~/.config/starship.toml
format = """
$directory\
$git_branch\
$fill\
$package\
$python\
$line_break\
$character"""

palette = "nord"


[fill]
symbol = ' '

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false

[docker_context]
symbol = " "

[git_branch]
style = 'fg:green'
symbol = " "
format = '[on](white) [$symbol$branch ]($style)'

[package]
style = 'bold orange'
format = '[${symbol}${version}]($style) '

[python]
style = 'teal'
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ""

[palettes.nord]
dark_blue = '#5E81AC'
teal = '#88C0D0'
green = '#A3BE8C'
red = '#BF616A'
orange = '#D08770'
white = 'D8DEE9'
